default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auction_player_system_development

test:
  <<: *default
  database: auction_player_system_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

queue:
  <<: *default
  url: <%= ENV["QUEUE_DATABASE_URL"] || ENV["DATABASE_URL"] %>

cache:
  <<: *default
  url: <%= ENV["CACHE_DATABASE_URL"] || ENV["DATABASE_URL"] %>
