default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: auction_player_system_development

test:
  <<: *default
  database: auction_player_system_test

production:
  primary:
    <<: *default
    database: auction_player_system_production
    username: auction_player_system
    password: <%= ENV["AUCTION_PLAYER_SYSTEM_DATABASE_PASSWORD"] %>

  queue:
    <<: *default
    database: auction_player_system_queue
    username: auction_player_system
    password: <%= ENV["AUCTION_PLAYER_SYSTEM_DATABASE_PASSWORD"] %>

  cache:
    <<: *default
    database: auction_player_system_cache
    username: auction_player_system
    password: <%= ENV["AUCTION_PLAYER_SYSTEM_DATABASE_PASSWORD"] %>
